# Generated by Django 5.1.3 on 2024-11-19 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0003_remove_horario_hora_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='hora_inicio',
            new_name='hora',
        ),
    ]
