# Generated by Django 5.1.3 on 2024-11-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_turnos', '0009_alter_turno_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
